function percentile = findpercentile(theta)
global setts
denominator = quadgk(@(x) exp(logPost(x)),-Inf, Inf, ...
    'AbsTol', setts.tol.findpercentile.AbsTol, ...
    'RelTol', setts.tol.findpercentile.RelTol);
numerator = quadgk(@(x) exp(logPost(x)),-Inf, theta, ...
    'AbsTol', setts.tol.findpercentile.AbsTol, ...
    'RelTol', setts.tol.findpercentile.RelTol);
percentile = numerator / denominator;
end
